version: "3.7"

services:
    # image project
    app:
        container_name: web-pdevo
        build:
            args:
              user: argos
              uid: 1000
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        # depends_on:
        #     - redis
        networks:
            - pdevo

    # nginx
    nginx:
        container_name: nginx-pdevo
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks:
            - pdevo

    # db mysql
    mysql:
        container_name: mysql-pdevo
        image: mariadb:latest
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - pdevo

    # # queue
    # queue:
    #     container_name: especializati-queue
    #     image: especializati/laravel-app
    #     restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         - redis
    #         - app
    #     networks:
    #         - laravel

    # # redis
    # redis:
    #     container_name: especializati-redis
    #     image: redis:latest
    #     networks:
    #         - laravel

networks:
    pdevo:
        driver: bridge


volumes:
      app:
      nginx:
      mysql:
